# -*- coding: utf-8 -*-
"""analysis of drawing of children

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/abdallahmahmoudkamel/analysis-of-drawing-of-children.a1dee06d-be4d-45db-9cf6-044f5381f6f6.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260627/auto/storage/goog4_request%26X-Goog-Date%3D20260627T115551Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D5471deacd6457c87b4496321b2b9360523453d2dbfe3c0dd2368c7da363a7536db0c46d66e299073d2fd1cd9094c97fd3a6f805724b9bcb5313e142eedcfe86fad32eb032844c135a808e18cb178339f1ae2bd22dbefe39de7b7ce6211d0eaad16591bbaca0631e1bfe8d74310cd6bfcadf5cb08bb5c4d769fddb5ebeb4a5187dcf3667fe44a600570d48f87c8aa7fc7da46e472efe65f113736da0e382cb0f240311997c8c86eabc8fd584ba5714a3493f1d9ccee0112922c4695a0cbbf91c9e3a61df4977a85384e54e1aeb9b949e61cf21a91a4d7305909a94510a6f396f7187c1b5f1037c7e847fff11d759580d0bff493e1c75c4594d5a73f2e3d925658
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import keras
import os

def create_data_set(path):
  images = []
  labels = []
  folders = os.listdir(path)
  for folder in folders:
    folder_path = os.path.join(path , folder)
    files = os.listdir(folder_path)
    for fil in files:
      file_path = os.path.join(folder_path , fil)
      images.append(file_path)
      labels.append(folder)
  data = pd.DataFrame({"file_paths":images , "labels":labels})
  return data

data = create_data_set("/kaggle/input/sent-analysis-for-children/Dataset Folder")
data

from sklearn.model_selection import train_test_split

train , dummy =  train_test_split(data , test_size = 0.2 , random_state = 44 , stratify=data["labels"])
testing , validation = train_test_split(dummy , test_size = 0.5 , random_state = 44)

label_counts = train["labels"].value_counts()
label_counts

label_counts = train["labels"].value_counts()

plt.bar(train["labels"].unique() , label_counts.values)
plt.xlabel("labels_of_training")
plt.ylabel("Freaquency")
plt.title("Distribution_of_labels")

plt.pie(label_counts.values , labels = train["labels"].unique() , explode = [0.1 , 0.1 , 0.1 , 0.1] , autopct="%0.2f%%")

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_gen = ImageDataGenerator(
    rotation_range=10,               #small rotation
    width_shift_range=0.05,          # Small horizontal shift
    height_shift_range=0.05,         # Small vertical shift
    zoom_range=0.05,                 # Small zoom in/out
    brightness_range=[0.9, 1.1],     # Slight brightness change
    shear_range=5,                   # Mild shearing (optional)
    fill_mode='nearest',             # Fill in gaps after shift/rotation
    rescale=1./255                   # Normalize pixel values
)

test_gen = ImageDataGenerator(rescale = 1./255)

import warnings
warnings.filterwarnings("ignore")

train_augmentated = train_gen.flow_from_dataframe(train,x_col= "file_paths" , y_col="labels" , target_size=(256 , 256) , color_mode="rgb" , class_mode="categorical" , batch_size=16, shuffle = True)
val= test_gen.flow_from_dataframe(validation , x_col="file_paths", y_col = "labels" , target_size=(256 , 256) , color_mode = "rgb" , class_mode = "categorical" , batch_size=16 , shuffle = False)
test= test_gen.flow_from_dataframe(testing, x_col="file_paths", y_col = "labels" , target_size=(256 , 256) , color_mode = "rgb" , class_mode = "categorical" , batch_size=16 , shuffle = False)

images,labels = next(train_augmentated)
classes_of_images = np.argmax(labels , axis = 1)
class_names = list(train_augmentated.class_indices.keys())

batch_size = 16
plt.figure(figsize=(15, 10))
for i,image in enumerate(images):
    plt.subplot(4, 4, i + 1)
    plt.imshow(image)
    plt.title(f"Class: {class_names[classes_of_images[i]]}")
    plt.axis('off')
plt.tight_layout()
plt.show()

from tensorflow.keras.applications import EfficientNetB3

base_model = EfficientNetB3(include_top=False , weights = "imagenet" , input_shape=(256,256,3))

from tensorflow.keras.layers import Dense,Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.models import Sequential

model = Sequential([
    base_model,
    Flatten(),
    #Dense(32,activation = "relu"),
    Dropout(0.3),
    Dense(train["labels"].nunique() , activation = "softmax")
])
model.summary()

model.compile("adam" , loss = "categorical_crossentropy" , metrics = ["accuracy"])

from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor = "val_accuracy" , patience =10 , restore_best_weights = True)

history = model.fit(train_augmentated , epochs = 50 , validation_data = val ,batch_size = 16 , callbacks = [early_stopping])

val_loss,val_accuracy = model.evaluate(val)
testing_loss,testing_accuracy = model.evaluate(test)
print(f"validation loss {val_loss}")
print(f"validation accuracy {val_accuracy}")
print("------------------")
print(f"testing_loss {testing_loss}")
print(f"testing_accuracy {testing_accuracy}")

plt.plot(history.history["accuracy"])
plt.plot(history.history["val_accuracy"])
plt.xlabel("epochs")

plt.ylabel("accuracy")
plt.legend(["train", "validation"] , loc = "upper left")
plt.show()

plt.plot(history.history["loss"])
plt.plot(history.history["val_loss"])
plt.xlabel("epochs")

plt.ylabel("loss")
plt.legend(["train", "validation"] , loc = "upper left")
plt.show()

predictions = model.predict(test)
predicts = np.argmax(predictions , axis =1)

from sklearn.metrics import classification_report,confusion_matrix

print(classification_report(test.classes , predicts))
cm = confusion_matrix(test.classes , predicts)

import seaborn as sns

labels = testing["labels"].unique()
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels, yticklabels=labels)

plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix Heatmap')
plt.show()

Model = model.save("my_model_analysis.h5")

testing["labels"].unique()

val.class_indices

paths = list(testing["file_paths"])
paths[1]